
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzzpiyabivlpsoehcnls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6enBpeWFiaXZscHNvZWhjbmxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NjUzMTYsImV4cCI6MjA2MzI0MTMxNn0.2SsDzfM1Hr27OPCW9I31C1fRsncvtH-XeuGeV-TDj18";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
